name: ⛅ Deploy Dev Workers
on:
  push:
    branches:
      - '**'        # All branch
      - '!master'   # Excludes master
  pull_request:
    branches:
      - '**'        # All branch
      - '!master'   # Excludes master
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm i
      - run: sed -i s/IPPROXYHERE/35.219.50.99/g src/panel.ts
      - run: sed -i s/IPPROXYHERE/35.219.50.99/g src/vless.ts
      - run: sed -i s/vpn/${{ github.ref_name }}/g wrangler.toml
      - run: sed -i s/KV_DEV/${{ secrets.KV_DEV }}/g wrangler.toml
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
